// Página accesible sin autenticación: no cargamos Firebase aquí para evitar logs 400.
// Mostramos login y ocultamos salir.
try {
  document.getElementById('user-email').textContent = '';
  document.getElementById('logout-btn').style.display = 'none';
  document.getElementById('login-link').style.display = 'inline-block';
} catch (_) {}

let headers = [];
let headerIndices = {};
const norm = (s)=> String(s||'').trim().toUpperCase().replace(/\s+/g,' ');
function getHeaderIndex(variants){ for (const v of variants){ const nv=norm(v); for (let i=0;i<headers.length;i++){ if (norm(headers[i])===nv) return i; } } return -1; }

async function loadHeaders(){ try{ const resp = await fetch('docs/REGISTRO DE ACTIVIDAD PCT 2025.csv'); const text = await resp.text(); const lines = text.split('\n'); for (let i=0;i<Math.min(20,lines.length);i++){ const cells = lines[i].split(','); if (cells.some(c=>/propiedad|serial|equipo|cliente/i.test(c))){ headers = cells.map(c=>c.trim()); headerIndices = { PROPIEDAD:getHeaderIndex(['PROPIEDAD']), SERIAL:getHeaderIndex(['SERIAL','#']), EQUIPO:getHeaderIndex(['EQUIPO / ACTIVO','EQUIPO/ACTIVO','EQUIPO ACTIVO','EQUIPO']), DESCRIPCION:getHeaderIndex(['DESCRIPCION','DESCRIPCIÓN']), CLIENTE:getHeaderIndex(['CLIENTE']), AREA:getHeaderIndex(['AREA DEL CLIENTE','ÁREA DEL CLIENTE']), UBICACION:getHeaderIndex(['UBICACION','UBICACIÓN']), FACTURA:getHeaderIndex(['FACTURA']), INICIO:getHeaderIndex(['INICIO DEL SERVICIO']), TERMINACION:getHeaderIndex(['TERMINACION DEL SERVICIO','TERMINACIÓN DEL SERVICIO']), DEVOLUCION:getHeaderIndex(['FECHA DE DEVOLUCION','FECHA DE DEVOLUCIÓN']), DIAS:getHeaderIndex(['DIAS EN SERVICIO','DÍAS EN SERVICIO']), PRECIO:getHeaderIndex(['PRECIO']), INGRESO:getHeaderIndex(['INGRESO ACUMULADO','INGRESO ACUMULDDO']), RENTA:getHeaderIndex(['RENTA ACUMULADA']) }; break; } } }catch(e){ console.error('[regactividad] headers:',e);} }

function loadHistory(){ try{ const key='actividad:newRows'; const stored=localStorage.getItem(key); const rows = stored? JSON.parse(stored):[]; if (rows.length===0){ document.getElementById('historyTableBody').innerHTML = '<tr><td colspan="12" style="text-align:center; padding:40px;">No hay registros guardados</td></tr>'; return; } let totalInternos=0,totalExternos=0,sumaIngreso=0,sumaRenta=0; rows.forEach(r=>{ const tipo=r[headerIndices.PROPIEDAD]||''; if (tipo==='PCT') totalInternos++; else if (tipo) totalExternos++; const ingreso=parseFloat(String(r[headerIndices.INGRESO]||'0').replace(/[^0-9.-]/g,''))||0; const renta=parseFloat(String(r[headerIndices.RENTA]||'0').replace(/[^0-9.-]/g,''))||0; sumaIngreso+=ingreso; sumaRenta+=renta; }); document.getElementById('totalRegistros').textContent=rows.length; document.getElementById('totalInternos').textContent=totalInternos; document.getElementById('totalExternos').textContent=totalExternos; document.getElementById('ingresoTotal').textContent='$'+sumaIngreso.toLocaleString('es-MX',{minimumFractionDigits:2}); document.getElementById('rentaTotal').textContent='$'+sumaRenta.toLocaleString('es-MX',{minimumFractionDigits:2}); renderTable(rows); }catch(e){ console.error('[regactividad] load:',e); document.getElementById('historyTableBody').innerHTML='<tr><td colspan="12" style="text-align:center; padding:40px; color:red;">Error al cargar registros</td></tr>'; } }

function renderTable(rows){ const tbody=document.getElementById('historyTableBody'); tbody.innerHTML=''; rows.forEach((row,idx)=>{ const tr=document.createElement('tr'); const tdF=document.createElement('td'); tdF.textContent=new Date().toLocaleDateString('es-MX'); tr.appendChild(tdF); const tdT=document.createElement('td'); const prop=row[headerIndices.PROPIEDAD]||''; const tipo=prop==='PCT'?'INTERNO':'EXTERNO'; tdT.innerHTML=`<span class="badge ${prop==='PCT'?'badge-interno':'badge-externo'}">${tipo}</span>`; tr.appendChild(tdT); const makeTd=(val)=>{const td=document.createElement('td'); td.textContent=val||'-'; return td;}; tr.appendChild(makeTd(row[headerIndices.SERIAL])); tr.appendChild(makeTd(row[headerIndices.EQUIPO])); tr.appendChild(makeTd(row[headerIndices.CLIENTE])); tr.appendChild(makeTd(row[headerIndices.INICIO])); tr.appendChild(makeTd(row[headerIndices.TERMINACION])); const tdDias=makeTd(row[headerIndices.DIAS]||'0'); tdDias.style.textAlign='center'; tr.appendChild(tdDias); const tdPrec=document.createElement('td'); const prec=parseFloat(row[headerIndices.PRECIO]||0); tdPrec.textContent='$'+prec.toLocaleString('es-MX',{minimumFractionDigits:2}); tdPrec.style.textAlign='right'; tr.appendChild(tdPrec); const tdMon=document.createElement('td'); const ing=parseFloat(row[headerIndices.INGRESO]||0); const ren=parseFloat(row[headerIndices.RENTA]||0); const monto=prop==='PCT'?ing:ren; tdMon.textContent='$'+monto.toLocaleString('es-MX',{minimumFractionDigits:2}); tdMon.style.textAlign='right'; tdMon.style.fontWeight='600'; tr.appendChild(tdMon); const tdEst=document.createElement('td'); const sTerm=row[headerIndices.TERMINACION]; let est='Desconocido'; if (sTerm){ const [d,m,y]=sTerm.split('/'); const f=new Date(2000+parseInt(y),parseInt(m)-1,parseInt(d)); est=f>new Date()?'Activo':'Finalizado'; } tdEst.innerHTML=`<span class="badge ${est==='Activo'?'badge-activo':'badge-finalizado'}">${est}</span>`; tr.appendChild(tdEst); const tdAcc=document.createElement('td'); tdAcc.style.whiteSpace='nowrap'; const bPdf=document.createElement('button'); bPdf.className='pdf-row-btn'; bPdf.innerHTML='📄'; bPdf.title='Generar PDF'; bPdf.style.marginRight='8px'; bPdf.onclick=()=>generatePDF(row); const bEd=document.createElement('button'); bEd.className='edit-row-btn'; bEd.innerHTML='✏️'; bEd.title='Editar'; bEd.style.marginRight='8px'; bEd.onclick=()=>editRecord(idx,row); const bDel=document.createElement('button'); bDel.className='delete-row-btn'; bDel.innerHTML='🗑️'; bDel.title='Eliminar'; bDel.onclick=()=>deleteRecord(idx,row); tdAcc.append(bPdf,bEd,bDel); tr.appendChild(tdAcc); tbody.appendChild(tr); }); }

function deleteRecord(index,row){ if(!confirm('¿Estás seguro de eliminar este registro permanentemente?')) return; try{ const key='actividad:newRows'; const stored=localStorage.getItem(key); const rows=stored?JSON.parse(stored):[]; rows.splice(index,1); localStorage.setItem(key,JSON.stringify(rows)); loadHistory(); console.log('[regactividad] Registro eliminado'); }catch(e){ console.error('[regactividad] del:',e); alert('Error al eliminar'); } }

function esc(v){ return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;'); }
function generatePDF(row){ const prop=row[headerIndices.PROPIEDAD]||''; const tipo=prop==='PCT'?'EQUIPO INTERNO':'EQUIPO EXTERNO'; const fecha=new Date().toLocaleDateString('es-MX',{year:'numeric',month:'long',day:'numeric'}); const ingreso=parseFloat(row[headerIndices.INGRESO]||0); const renta=parseFloat(row[headerIndices.RENTA]||0); const monto=prop==='PCT'?ingreso:renta; const montoLabel=prop==='PCT'?'Ingreso Acumulado':'Renta Acumulada'; const html=['<!DOCTYPE html>','<html lang="es"><head><meta charset="UTF-8"><title>Registro de Actividad - '+esc(row[headerIndices.EQUIPO]||'Sin Equipo')+'</title><style>body{font-family:Arial,sans-serif;margin:24px;} h1{color:#d97706;margin:0 0 6px} .sec{margin:18px 0} .grid{display:grid;grid-template-columns:1fr 1fr;gap:10px 20px} .item{border-bottom:1px solid #e5e7eb;padding:6px 0} .lab{font-size:12px;color:#6b7280;text-transform:uppercase} .val{font-weight:600} .right{text-align:right}</style></head><body>', '<h1>PCT CONSTRUCCIÓN</h1><div>'+esc(tipo)+' • '+esc(fecha)+'</div>', '<div class="sec"><div class="lab">Serial</div><div class="val">'+esc(row[headerIndices.SERIAL]||'N/A')+'</div></div>', '<div class="sec grid">', '<div class="item"><div class="lab">Equipo / Activo</div><div class="val">'+esc(row[headerIndices.EQUIPO]||'N/A')+'</div></div>', '<div class="item"><div class="lab">Cliente</div><div class="val">'+esc(row[headerIndices.CLIENTE]||'N/A')+'</div></div>', '<div class="item"><div class="lab">Inicio</div><div class="val">'+esc(row[headerIndices.INICIO]||'N/A')+'</div></div>', '<div class="item"><div class="lab">Terminación</div><div class="val">'+esc(row[headerIndices.TERMINACION]||'N/A')+'</div></div>', '<div class="item"><div class="lab">Días</div><div class="val">'+esc(row[headerIndices.DIAS]||'0')+'</div></div>', '<div class="item"><div class="lab">Precio</div><div class="val right">$'+(parseFloat(row[headerIndices.PRECIO]||0).toLocaleString('es-MX',{minimumFractionDigits:2}))+'</div></div>', '<div class="item"><div class="lab">'+esc(montoLabel)+'</div><div class="val right">$'+(monto.toLocaleString('es-MX',{minimumFractionDigits:2}))+'</div></div>', '</div>', '</body></html>'].join(''); const pw=window.open('','_blank'); pw.document.open('text/html'); pw.document.write(html); pw.document.close(); pw.focus(); try{pw.print();}catch(e){} setTimeout(()=>{try{pw.close();}catch(e){}},600); }

function editRecord(){ alert('Edición en desarrollo. Por ahora, edita desde "Registro de actividad"'); }

// Arranque: cargar datos siempre (sin auth en esta página)
(async function init(){
  await loadHeaders();
  loadHistory();
})();

document.querySelector('.menu-toggle')?.addEventListener('click', function(){ const nav=document.getElementById('primary-nav'); nav.classList.toggle('open'); this.setAttribute('aria-expanded', nav.classList.contains('open')); });

document.getElementById('searchInput')?.addEventListener('input', (e)=>{ const term=e.target.value.toLowerCase(); document.querySelectorAll('#historyTableBody tr').forEach(r=>{ r.style.display = r.textContent.toLowerCase().includes(term)?'':'none'; }); });

document.getElementById('exportBtn')?.addEventListener('click', function(){ try{ const key='actividad:newRows'; const stored=localStorage.getItem(key); const rows=stored?JSON.parse(stored):[]; if(rows.length===0){ alert('No hay registros para exportar'); return; } const headersCsv='Tipo,Serial,Equipo/Activo,Descripción,Cliente,Área,Ubicación,Factura,Inicio,Terminación,Días,Precio,Ingreso/Renta\n'; let csv=headersCsv; rows.forEach(row=>{ const prop=row[headerIndices.PROPIEDAD]||''; const tipo=prop==='PCT'?'INTERNO':'EXTERNO'; const ingreso=parseFloat(row[headerIndices.INGRESO]||0); const renta=parseFloat(row[headerIndices.RENTA]||0); const monto=prop==='PCT'?ingreso:renta; const fields=[ tipo, row[headerIndices.SERIAL]||'', row[headerIndices.EQUIPO]||'', row[headerIndices.DESCRIPCION]||'', row[headerIndices.CLIENTE]||'', row[headerIndices.AREA]||'', row[headerIndices.UBICACION]||'', row[headerIndices.FACTURA]||'', row[headerIndices.INICIO]||'', row[headerIndices.TERMINACION]||'', row[headerIndices.DIAS]||'', row[headerIndices.PRECIO]||'', monto||'' ]; const line=fields.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(','); csv+=line+'\n'; }); const blob=new Blob([csv],{type:'text/csv;charset=utf-8;'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='historial_actividad_'+new Date().toISOString().split('T')[0]+'.csv'; a.click(); }catch(e){ console.error('[regactividad] export:',e); alert('Error al exportar CSV'); } });

document.getElementById('clearAllBtn')?.addEventListener('click', function(){ if(!confirm('⚠️ ADVERTENCIA: Esto eliminará TODOS los registros permanentemente.\n\n¿Estás completamente seguro?')) return; if(!confirm('Esta acción NO se puede deshacer. ¿Continuar?')) return; try{ localStorage.removeItem('actividad:newRows'); loadHistory(); alert('✅ Todos los registros han sido eliminados'); }catch(e){ console.error('[regactividad] clear:',e); alert('Error al borrar'); } });

document.getElementById('refreshBtn')?.addEventListener('click', async ()=>{ await loadHeaders(); loadHistory(); });
